@extends('layouts.dashboard')

@section('content')
<div class="container py-4">
    <form action="{{ isset($flashcardSet) ? route('teacher.flashcard-sets.update', $flashcardSet->id) : route('teacher.flashcard-sets.store') }}" method="POST" id="flashcardForm">
        @csrf
        @if(isset($flashcardSet))
            @method('PUT')
        @endif
        
        <!-- Top Bar -->
        <div class="mb-3">
             <a href="{{ route('teacher.flashcard-sets.index') }}" class="btn btn-outline-secondary btn-sm">
                <i class="bi bi-arrow-left me-1"></i> Back to Flashcards
            </a>
        </div>
        <div class="d-flex justify-content-between align-items-center mb-4">
            <h3 class="mb-0 fw-bold">{{ isset($flashcardSet) ? 'Edit flashcard set' : 'Create a new flashcard set' }}</h3>
            <div>
                <button type="submit" class="btn btn-primary fw-bold px-4 py-2">{{ isset($flashcardSet) ? 'Update' : 'Create' }}</button>
            </div>
        </div>

        <!-- Meta Info -->
        <div class="card shadow-sm border-0 mb-5">
            <div class="card-body p-4">
                <div class="mb-4">
                    <label class="form-label text-muted small fw-bold text-uppercase">Title</label>
                    <input type="text" name="title" class="form-control form-control-lg" placeholder="Enter a Title" value="{{ old('title', $flashcardSet->title ?? '') }}" required>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label class="form-label text-muted small fw-bold text-uppercase">Topic</label>
                        <select name="topic" class="form-select" required>
                            <option value="" disabled {{ !isset($flashcardSet->topic) ? 'selected' : '' }}>Select a Topic</option>
                            @foreach($topics as $t)
                                <option value="{{ $t->name }}" {{ (old('topic', $flashcardSet->topic ?? request('topic')) == $t->name) ? 'selected' : '' }}>{{ $t->name }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                         <label class="form-label text-muted small fw-bold text-uppercase">Description</label>
                         <textarea name="description" class="form-control" placeholder="Add a description..." rows="2" style="resize: none;">{{ old('description', $flashcardSet->description ?? '') }}</textarea>
                    </div>
                </div>
            </div>
        </div>

        <!-- Cards Actions -->
        <div class="d-flex justify-content-end mb-2">
            <button type="button" class="btn btn-outline-danger btn-sm fw-bold" id="delete-all-btn" title="Delete All Cards">
                <i class="bi bi-trash3-fill me-1"></i> Delete All
            </button>
        </div>

        <!-- Cards Container -->
        <div id="cards-container">
            <!-- Initial Card (will be generated by JS or Blade) -->
        </div>

        <!-- Add Card & AI Generate Buttons -->
        <div class="row g-3 mb-5">
            <div class="col-md-6">
                <div class="card shadow-sm border-0" style="cursor: pointer; transition: all 0.2s;" id="add-card-btn">
                    <div class="card-body py-4 text-center">
                        <h5 class="fw-bold mb-0 text-primary text-uppercase">+ Add a card</h5>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card shadow-sm border-0" style="cursor: pointer; transition: all 0.2s; background: linear-gradient(135deg, #f0f4c3 0%, #ffffff 100%); border: 1px dashed #c0ca33 !important;" id="csv-import-btn">
                    <div class="card-body py-4 text-center">
                        <h5 class="fw-bold mb-0 text-success text-uppercase"><i class="bi bi-file-earmark-spreadsheet"></i> Import from CSV/Excel</h5>
                        <input type="file" id="csv-file-input" class="d-none" accept=".csv, .txt, .xlsx, .xls">
                    </div>
                </div>
            </div>
        </div>

    </form>
</div>

<!-- Template for a Card Row -->
<template id="card-template">
    <div class="card shadow-sm border-0 mb-3 flashcard-row">
        <div class="card-body p-4">
            <div class="d-flex justify-content-between border-bottom pb-3 mb-3">
                <span class="card-index fw-bold text-muted h5 mb-0">1</span>
                <div>
                     <button type="button" class="btn btn-link text-muted p-0 delete-row"><i class="bi bi-trash fs-5"></i></button>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="mb-2 focused-input-container">
                         <input type="text" class="form-control card-term form-control-lg bg-light border-0 border-bottom border-3" placeholder="Enter term" required>
                         <label class="text-uppercase text-muted small fw-bold mt-2">Term</label>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="mb-2 focused-input-container">
                         <input type="text" class="form-control card-definition form-control-lg bg-light border-0 border-bottom border-3" placeholder="Enter definition" required>
                         <label class="text-uppercase text-muted small fw-bold mt-2">Definition</label>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

@endsection

@push('styles')
<style>
    .flashcard-perspective {
        perspective: 1000px;
    }
    .flashcard-inner {
        position: relative;
        width: 100%;
        height: 100%;
        text-align: center;
        transition: transform 0.6s cubic-bezier(0.4, 0.2, 0.2, 1);
        transform-style: preserve-3d;
        cursor: pointer;
    }
    .flashcard-inner.is-flipped {
        transform: rotateY(180deg);
    }
    .flashcard-face {
        position: absolute;
        width: 100%;
        height: 100%;
        -webkit-backface-visibility: hidden;
        backface-visibility: hidden;
        border-radius: 1rem;
        box-shadow: 0 10px 30px rgba(0,0,0,0.3); /* Premium shadow */
        background-color: #212529; /* Deep Charcoal for Front */
        color: white;
        display: flex;
        flex-direction: column;
    }
    .flashcard-back {
        transform: rotateY(180deg);
        background-color: #343a40; /* Graphite Grey for Back */
    }
    .flashcard-input {
        background: transparent !important;
        border: none !important;
        color: white !important;
        font-size: 1.5rem;
        text-align: center;
        width: 100%;
        height: 100%;
        resize: none;
    }
    .flashcard-input:focus {
        box-shadow: none !important;
        outline: none !important;
    }
    .flashcard-input::placeholder {
        color: rgba(255, 255, 255, 0.4);
    }
</style>
@endpush

@push('scripts')
<script src="https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const container = document.getElementById('cards-container');
        const addBtn = document.getElementById('add-card-btn');
        let cardCount = 0;

        function getCardHtml(index, term = '', definition = '') {
            return `
            <div class="row justify-content-center mb-5 flashcard-row" data-id="${index}">
                <div class="col-md-1 position-relative d-flex flex-column align-items-center justify-content-start pt-3">
                     <span class="drag-handle text-muted mb-2" style="cursor: grab;"><i class="bi bi-grip-horizontal fs-4"></i></span>
                     <span class="h4 fw-bold text-muted mb-3 card-index">${index}</span>
                     <button type="button" class="btn btn-outline-danger btn-sm rounded-circle delete-row" style="width: 32px; height: 32px; padding: 0;"><i class="bi bi-trash"></i></button>
                </div>
                <div class="col-md-8">
                    <div class="flashcard-perspective" style="height: 300px;">
                        <div class="flashcard-inner">
                            
                            <!-- Front Face -->
                            <div class="flashcard-face flashcard-front p-4">
                                <div class="d-flex justify-content-between align-items-center mb-2">
                                    <span class="badge bg-info bg-opacity-25 text-info border border-info fw-bold">FRONT</span>
                                    <small class="text-white-50"><i class="bi bi-hand-index-thumb"></i> Tap to flip</small>
                                </div>
                                <div class="flex-grow-1 d-flex align-items-center">
                                    <textarea name="flashcards[${index-1}][term]" class="form-control flashcard-input" placeholder="Type front text here..." required>${term}</textarea>
                                </div>
                            </div>

                            <!-- Back Face -->
                            <div class="flashcard-face flashcard-back p-4">
                                <div class="d-flex justify-content-between align-items-center mb-2">
                                    <span class="badge bg-warning bg-opacity-25 text-warning border border-warning fw-bold">BACK</span>
                                    <small class="text-white-50"><i class="bi bi-hand-index-thumb"></i> Tap to flip</small>
                                </div>
                                <div class="flex-grow-1 d-flex align-items-center">
                                    <textarea name="flashcards[${index-1}][definition]" class="form-control flashcard-input" placeholder="Type back text here..." required>${definition}</textarea>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            `;
        }

        function addCard(data = null) {
            cardCount++;
            const term = data ? data.term : '';
            const definition = data ? data.definition : '';
            
            const tempDiv = document.createElement('div');
            tempDiv.innerHTML = getCardHtml(cardCount, term, definition);
            const newCardRow = tempDiv.firstElementChild;

            // Flip Logic
            const innerCard = newCardRow.querySelector('.flashcard-inner');
            const inputs = newCardRow.querySelectorAll('textarea');

            // Handle Flip
            innerCard.addEventListener('click', function(e) {
                if (e.target.tagName.toLowerCase() === 'textarea') return;
                this.classList.toggle('is-flipped');
            });

            inputs[0].addEventListener('focus', () => innerCard.classList.remove('is-flipped')); 
            inputs[1].addEventListener('focus', () => innerCard.classList.add('is-flipped'));

            // Delete Logic
            newCardRow.querySelector('.delete-row').addEventListener('click', function(e) {
                if (document.querySelectorAll('.flashcard-row').length > 1) {
                    newCardRow.remove();
                    reindexCards();
                } else {
                    alert('You must have at least one card.');
                }
            });

            container.appendChild(newCardRow);
        }

        function reindexCards() {
            const rows = container.querySelectorAll('.flashcard-row');
            rows.forEach((row, index) => {
                const newIndex = index + 1;
                row.querySelector('span.h4').textContent = newIndex;
                const termInput = row.querySelector('textarea[name*="[term]"]');
                const defInput = row.querySelector('textarea[name*="[definition]"]');
                termInput.name = `flashcards[${index}][term]`;
                defInput.name = `flashcards[${index}][definition]`;
            });
            cardCount = rows.length;
        }

        if(addBtn) {
            addBtn.addEventListener('click', () => addCard());
            
            const initialCards = @json($flashcardSet->flashcards ?? []);
            
            if (initialCards.length > 0) {
                initialCards.forEach(card => addCard(card));
            }
        }

        // --- File Import Logic ---
        const fileImportBtn = document.getElementById('csv-import-btn');
        const fileInput = document.getElementById('csv-file-input');

        if(fileImportBtn && fileInput) {
            fileImportBtn.addEventListener('click', (e) => {
                if(e.target !== fileInput) {
                    fileInput.click();
                }
            });

            fileInput.addEventListener('change', function(e) {
                if (this.files.length === 0) return;

                const file = this.files[0];
                const originalText = fileImportBtn.querySelector('h5').innerHTML;
                fileImportBtn.querySelector('h5').innerHTML = '<i class="bi bi-hourglass-split"></i> Parsing file...';
                fileImportBtn.style.pointerEvents = 'none';

                const reader = new FileReader();
                reader.onload = function(e) {
                    try {
                        const data = new Uint8Array(e.target.result);
                        const workbook = XLSX.read(data, {type: 'array'});
                        const firstSheetName = workbook.SheetNames[0];
                        const worksheet = workbook.Sheets[firstSheetName];
                        
                        // Convert to JSON (array of arrays)
                        const json = XLSX.utils.sheet_to_json(worksheet, {header: 1});
                        
                        let importedCount = 0;
                        if (json.length > 0) {
                            // Find column indices
                            let termIdx = 0;
                            let defIdx = 1;
                            
                            const headerRow = json[0].map(h => String(h).toLowerCase().trim());
                            
                            // Try to find specific columns
                            const questionCol = headerRow.findIndex(h => h.includes('question') || h.includes('term'));
                            const answerCol = headerRow.findIndex(h => h.includes('answer') || h.includes('definition'));
                            
                            if (questionCol !== -1 && answerCol !== -1) {
                                termIdx = questionCol;
                                defIdx = answerCol;
                            } else if (headerRow.length >= 3 && (headerRow[0].includes('no') || headerRow[0] === '#')) {
                                // If no explicit headers but first column looks like "No.", shift over
                                termIdx = 1;
                                defIdx = 2;
                            }

                            json.forEach((row, index) => {
                                // Skip the header row if we detected headers
                                if (index === 0 && (questionCol !== -1 || row[termIdx]?.toString().toLowerCase().includes('term') || row[termIdx]?.toString().toLowerCase().includes('question'))) {
                                    return;
                                }

                                if (!row || row.length < 2) return;
                                
                                const term = row[termIdx] ? String(row[termIdx]).trim() : '';
                                const definition = row[defIdx] ? String(row[defIdx]).trim() : '';
                                
                                if (term && definition) {
                                    addCard({term: term, definition: definition});
                                    importedCount++;
                                }
                            });
                        }

                        if (importedCount > 0) {
                            const allCards = container.querySelectorAll('.flashcard-row');
                            if(allCards.length > 0) {
                                allCards[allCards.length - importedCount].scrollIntoView({ behavior: 'smooth' });
                            }
                            alert('Success! ' + importedCount + ' flashcards imported.');
                        } else {
                            alert('No valid flashcards found. Please ensure the file has at least two columns (Term, Definition).');
                        }

                    } catch (error) {
                        console.error(error);
                        alert('Error parsing file: ' + error.message);
                    } finally {
                        fileImportBtn.querySelector('h5').innerHTML = originalText;
                        fileImportBtn.style.pointerEvents = 'auto';
                        fileInput.value = '';
                    }
                };
                reader.onerror = function() {
                    alert('Error reading file.');
                    fileImportBtn.querySelector('h5').innerHTML = originalText;
                    fileImportBtn.style.pointerEvents = 'auto';
                    fileInput.value = '';
                }
                reader.readAsArrayBuffer(file);
            });
        }

        // --- Delete All Logic ---
        const deleteAllBtn = document.getElementById('delete-all-btn');
        if(deleteAllBtn) {
            deleteAllBtn.addEventListener('click', () => {
                if(confirm('Are you sure you want to delete ALL cards? This cannot be undone.')) {
                    container.innerHTML = '';
                    cardCount = 0;
                    // Optionally add one empty card back? 
                    // addCard(); 
                }
            });

        }

        // --- Drag and Drop Logic ---
        new Sortable(container, {
            animation: 150,
            handle: '.drag-handle',
            ghostClass: 'sortable-ghost',
            onEnd: function() {
                reindexCards();
            }
        });
        // --- Prevent Double Submission ---
        const flashcardForm = document.getElementById('flashcardForm');
        if (flashcardForm) {
            flashcardForm.addEventListener('submit', function(e) {
                const submitBtn = this.querySelector('button[type="submit"]');
                if (submitBtn) {
                    if (submitBtn.disabled) {
                        e.preventDefault();
                        return;
                    }
                    submitBtn.disabled = true;
                    submitBtn.innerHTML = '<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> Saving...';
                }
            });
        }
    });
</script>
@endpush
